version: '2'
services:
  controller:
    container_name: whaler
    build: ./agent
    image: whaler/agent
    restart: on-failure
    environment:
        - WHALER_DATA_DIR
        - LOGZIO_TOKEN
        - LOGZIO_ENV=whaler-test
        - LOGZIO_ZONE=us
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/tmp/whaler:/var/tmp/whaler
      - /:/host
    networks:
      - default
  

  victim: 
    image: docker:stable-dind
    privileged: true
    restart: on-failure
    ports:
      - "2375:2375"
    expose:
      - "2375"
    networks:
      - default
  

networks:
  default: