version: '2'
services:
  controller:
    container_name: whaler
    build: ./agent
    image: whaler/agent
    restart: on-failure
    environment:
        - CONTAINER_KILL_DELAY=15
        - LOGZIO_TOKEN
        - LOGZIO_ENV=whaler-test
        - LOGZIO_ZONE=us
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/whaler:/tmp/whaler
      - /:/host

  