version: '2'
services:
  controller:
    build: ./agent
    image: whaler/agent
    restart: on-failure
    environment:
        - CONTAINER_KILL_DELAY=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/whaler/snapshots:/tmp/whaler/snapshots
    depends_on:
      - victim

  victim:      
      image: docker:stable-dind
      privileged: true
      restart: on-failure
      ports:
        - "2375:2375"
      expose:
      - "2375"

  capture:
    build: ./capture
    image: whaler/capture
    restart: on-failure
    depends_on:
      - victim
    network_mode: service:victim
    volumes:
      - /tmp/whaler/capture:/tmp/whaler/capture  
  